import type { Scenario } from "@/shared/types";

export const SAMPLE_SCENARIOS: Scenario[] = [
  {
    id: "s1",
    title: "Evening Recovery Walk",
    subtitle: "A gentle evening to restore your energy in the old city",
    emoji: "🌙",
    moodTag: "Recover",
    totalDuration: "2 hours",
    weatherSuitability: "Clear skies",
    createdAt: new Date().toISOString(),
    params: {
      duration: "1-2h",
      timeOfDay: "evening",
      energyLevel: 2,
      mood: "recover",
      budget: "cheap",
      scenarioType: "walk",
      socialMode: "solo",
      city: "Prague",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "Slow Walk Through Old Town",
        description: "A peaceful 15-minute stroll through the quiet cobblestone streets of the old city. Set a slow pace and let your mind wander.",
        duration: "15 min",
        budgetEstimate: "Free",
        locationType: "outdoor",
        emoji: "🚶",
      },
      {
        id: "step2",
        order: 2,
        title: "Cozy Café Stop",
        description: "Find a warm, quiet café for a hot drink. Choose a window seat, relax, and watch the city slow down.",
        duration: "40 min",
        budgetEstimate: "€5–8",
        locationType: "indoor",
        emoji: "☕",
      },
      {
        id: "step3",
        order: 3,
        title: "Bookshop or Art Space",
        description: "Browse a local bookshop or small gallery. No pressure to buy — just explore and let curiosity guide you.",
        duration: "25 min",
        budgetEstimate: "Free",
        locationType: "indoor",
        emoji: "📚",
      },
      {
        id: "step4",
        order: 4,
        title: "Riverside Ending",
        description: "A short walk along the river to close the evening. Breathe in the cool air and let the day settle.",
        duration: "20 min",
        budgetEstimate: "Free",
        locationType: "outdoor",
        emoji: "🌊",
      },
    ],
  },
  {
    id: "s2",
    title: "Cultural Morning Exploration",
    subtitle: "Museums, coffee, and the best of the city's cultural scene",
    emoji: "🎨",
    moodTag: "Cultural",
    totalDuration: "3 hours",
    weatherSuitability: "Any weather",
    createdAt: new Date().toISOString(),
    params: {
      duration: "2-4h",
      timeOfDay: "morning",
      energyLevel: 4,
      mood: "cultural",
      budget: "medium",
      scenarioType: "culture",
      socialMode: "solo",
      city: "Prague",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "Morning Coffee Ritual",
        description: "Start with a specialty coffee at a local roastery. Take time to wake up slowly.",
        duration: "20 min",
        budgetEstimate: "€4–6",
        locationType: "indoor",
        emoji: "☕",
      },
      {
        id: "step2",
        order: 2,
        title: "Museum Visit",
        description: "Explore a local museum or gallery. Focus on one exhibition rather than trying to see everything.",
        duration: "90 min",
        budgetEstimate: "€8–15",
        locationType: "indoor",
        emoji: "🏛️",
      },
      {
        id: "step3",
        order: 3,
        title: "Local Market",
        description: "Browse a nearby farmers market or craft market. Sample local foods and chat with vendors.",
        duration: "40 min",
        budgetEstimate: "€5–10",
        locationType: "outdoor",
        emoji: "🛍️",
      },
    ],
  },
  {
    id: "s3",
    title: "Active City Adventure",
    subtitle: "High energy exploration of hidden city gems",
    emoji: "⚡",
    moodTag: "Explore",
    totalDuration: "4 hours",
    weatherSuitability: "Sunny",
    createdAt: new Date().toISOString(),
    params: {
      duration: "2-4h",
      timeOfDay: "afternoon",
      energyLevel: 5,
      mood: "explore",
      budget: "medium",
      scenarioType: "explore",
      socialMode: "friends",
      city: "Prague",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "Hidden Viewpoint",
        description: "Hike up to a lesser-known viewpoint for panoramic city views. Bring water.",
        duration: "45 min",
        budgetEstimate: "Free",
        locationType: "outdoor",
        emoji: "🏔️",
      },
      {
        id: "step2",
        order: 2,
        title: "Street Food Lunch",
        description: "Grab lunch from a local street food vendor. Try something you've never had before.",
        duration: "30 min",
        budgetEstimate: "€8–12",
        locationType: "outdoor",
        emoji: "🌮",
      },
      {
        id: "step3",
        order: 3,
        title: "Neighborhood Wander",
        description: "Explore a neighborhood you've never visited. No map, just instinct.",
        duration: "60 min",
        budgetEstimate: "Free",
        locationType: "outdoor",
        emoji: "🗺️",
      },
      {
        id: "step4",
        order: 4,
        title: "Rooftop Bar",
        description: "End the adventure with drinks at a rooftop bar. Watch the sunset over the city.",
        duration: "60 min",
        budgetEstimate: "€15–20",
        locationType: "indoor",
        emoji: "🍹",
      },
    ],
  },
];

export const MINI_ROUTES: Scenario[] = [
  {
    id: "mini1",
    title: "Quick Park Reset",
    subtitle: "10 minutes to clear your head",
    emoji: "🌿",
    moodTag: "Calm",
    totalDuration: "15 min",
    weatherSuitability: "Clear",
    createdAt: new Date().toISOString(),
    params: {
      duration: "15-30min",
      timeOfDay: "afternoon",
      energyLevel: 2,
      mood: "calm",
      budget: "free",
      scenarioType: "walk",
      socialMode: "solo",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "Park Walk",
        description: "A short walk through the nearest park. Leave your phone in your pocket.",
        duration: "15 min",
        budgetEstimate: "Free",
        locationType: "outdoor",
        emoji: "🌿",
      },
    ],
  },
  {
    id: "mini2",
    title: "Coffee & Stretch",
    subtitle: "Perfect work break",
    emoji: "☕",
    moodTag: "Productive",
    totalDuration: "20 min",
    weatherSuitability: "Any",
    createdAt: new Date().toISOString(),
    params: {
      duration: "15-30min",
      timeOfDay: "afternoon",
      energyLevel: 3,
      mood: "productive",
      budget: "cheap",
      scenarioType: "rest",
      socialMode: "solo",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "Coffee Break",
        description: "Step away from your desk and grab a coffee from a nearby café.",
        duration: "20 min",
        budgetEstimate: "€3–5",
        locationType: "indoor",
        emoji: "☕",
      },
    ],
  },
  {
    id: "mini3",
    title: "Lunch Wander",
    subtitle: "Discover a new spot nearby",
    emoji: "🍜",
    moodTag: "Explore",
    totalDuration: "40 min",
    weatherSuitability: "Any",
    createdAt: new Date().toISOString(),
    params: {
      duration: "30-60min",
      timeOfDay: "afternoon",
      energyLevel: 3,
      mood: "explore",
      budget: "medium",
      scenarioType: "food",
      socialMode: "solo",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "New Restaurant Discovery",
        description: "Walk in a direction you don't usually go and find somewhere new for lunch.",
        duration: "40 min",
        budgetEstimate: "€10–15",
        locationType: "indoor",
        emoji: "🍜",
      },
    ],
  },
  {
    id: "mini4",
    title: "Bookshop Browse",
    subtitle: "Quiet indoor exploration",
    emoji: "📖",
    moodTag: "Cozy",
    totalDuration: "30 min",
    weatherSuitability: "Rainy",
    createdAt: new Date().toISOString(),
    params: {
      duration: "15-30min",
      timeOfDay: "afternoon",
      energyLevel: 2,
      mood: "cozy",
      budget: "free",
      scenarioType: "culture",
      socialMode: "solo",
    },
    steps: [
      {
        id: "step1",
        order: 1,
        title: "Bookshop Visit",
        description: "Browse a local bookshop with no intention to buy. Just explore.",
        duration: "30 min",
        budgetEstimate: "Free",
        locationType: "indoor",
        emoji: "📖",
      },
    ],
  },
];

export interface SmartTrigger {
  icon: string;
  text: string;
  action: string;
}

export const SMART_TRIGGERS: SmartTrigger[] = [
  {
    icon: "☀️",
    text: "Perfect weather for an outdoor scenario today",
    action: "Create outdoor route →",
  },
  {
    icon: "🕕",
    text: "You have a free window in the evening",
    action: "Plan your evening →",
  },
  {
    icon: "⚡",
    text: "Quick 20-min break available now",
    action: "Get a mini route →",
  },
];
